import {
  feedsActive,
  feedsInactive,
  groupActive,
  groupInactive,
  homeActive,
  homeInactive,
  sessionsActive,
  sessionsInactive,
  adminApplications,
  adminApplicationsActive,
  adminNotifications,
  adminNotificationsActive,
  adminSettings,
  adminSettingsActive,
  adminSupport,
  adminSupportActive,
  adminUsers,
  adminUsersActive,
  adminWallet,
  adminWalletActive,
  dashboard,
  dashboardActive,
  logout,
  support,
  activeWebinar,
  inactiveWebinar,
  activeMentorship,
  inactiveMentorship,
} from "@/public/icons";

export const mainMenu = [
  {
    active: homeActive,
    inactive: homeInactive,
    title: "Home",
    url: "/find-consultants",
  },
  {
    active: feedsActive,
    inactive: feedsInactive,
    title: "Feeds",
    url: "/feeds",
  },
  {
    active: sessionsActive,
    inactive: sessionsInactive,
    title: "Sessions",
    url: "/sessions",
  },
  {
    active: groupActive,
    inactive: groupInactive,
    title: "Groups",
    url: "/groups",
  },
  {
    active: activeWebinar,
    inactive: inactiveWebinar,
    title: "Webinars",
    url: "/webinars",
  },
  
  {
    active: activeMentorship,
    inactive: inactiveMentorship,
    title: "Mentorships",
    url: "/mentorship",
  },
];

export const adminMenu = [
  {
    text: "Dashboard",
    to: "/admin/dashboard",
    icon: dashboard,
    active: dashboardActive,
  },
  {
    text: "Applications",
    to: "/admin/applications",
    icon: adminApplications,
    active: adminApplicationsActive,
  },
  {
    text: "Users",
    to: "/admin/users",
    icon: adminUsers,
    active: adminUsersActive,
  },
  {
    text: "Groups",
    to: "/admin/groups",
    icon: adminUsers,
    active: adminUsersActive,
  },
  {
    text: "Requests",
    to: "/admin/requests",
    icon: adminApplications,
    active: adminApplicationsActive,
  },
  {
    text: "All Sessions",
    to: "/admin/sessions",
    icon: adminApplications,
    active: adminApplicationsActive,
  },
  {
    text: "Wallet",
    to: "/admin/wallet",
    icon: adminWallet,
    active: adminWalletActive,
  },
  {
    text: "Articles",
    to: "/admin/articles",
    icon: adminApplications,
    active: adminApplicationsActive,
  },
  {
    text: "Post Permission Applications",
    to: "/admin/feed-applications",
    icon: adminApplications,
    active: adminApplicationsActive,
  },
  {
    text: "Blogs",
    to: "/admin/blogs",
    icon: adminApplications,
    active: adminApplicationsActive,
  },
  {
    text: "Support Tickets",
    to: "/admin/tickets",
    icon: adminSupport,
    active: adminSupportActive,
  },
  {
    text: "Notifications",
    to: "/admin/notifications",
    icon: adminNotifications,
    active: adminNotificationsActive,
  },
  {
    text: "Account",
    to: "/admin/account",
    icon: adminSettings,
    active: adminSettingsActive,
  },
  {
    text: "Settings",
    to: "/admin/settings",
    icon: adminSettings,
    active: adminSettingsActive,
  },
  {
    text: "Log Out", 
    to: "",
    icon: logout,
    active: logout,
  },

  // {
  //   text: "Terms and Condition",
  //   to: "/admin/terms-and-condition",
  //   icon: adminApplications,
  //   active: adminApplicationsActive,
  // },
  // {
  //   text: "Privacy policy",
  //   to: "/admin/privacy-policy",
  //   icon: adminApplications,
  //   active: adminApplicationsActive,
  // },
];
